In [4]:
import numpy as np

#creating vectors
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print("Vector v1:", v1)
print("Vector v2:", v2)

Vector v1: [1 2 3]
Vector v2: [4 5 6]


In [5]:
v_add = v1+v2
v_subtact = v1-v2


In [8]:
print (v_add)
print (v_subtact)

[5 7 9]
[-3 -3 -3]


In [12]:
scalar = 2
v_multiply = scalar * v1 
print(v_multiply)

[2 4 6]


In [14]:
#1*4 + 2*5 + 3*6
dot_product = np.dot(v1,v2)
print(dot_product)

32


In [15]:
#magnitude or length of a vector (the square root of the sum of all the squared elements)

magnitude_v1 = np.linalg.norm(v1)
print(magnitude_v1)

3.7416573867739413


In [21]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12],[13,14,15]])
print("A:", A)
print()
print("B:",B)

A: [[1 2 3]
 [4 5 6]]

B: [[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [24]:
C = np.array([[1,2,3],[4,5,6]])
matrix_add = A + C
matrix_subtract = A-C
print (matrix_add)
print ()
print(matrix_subtract)


[[ 2  4  6]
 [ 8 10 12]]

[[0 0 0]
 [0 0 0]]


In [25]:
matrix_mul = np.dot(A,B)
print(matrix_mul)

[[ 66  72  78]
 [156 171 186]]


In [26]:
transpose_A = A.T
print(transpose_A)

[[1 4]
 [2 5]
 [3 6]]


In [29]:
a = np.array([[2,3],[4,-1]])
b = np.array([5,3])
print(a)
print(b)

print()
x = np.linalg.solve(a,b)
print(x)

[[ 2  3]
 [ 4 -1]]
[5 3]

[1. 1.]


In [31]:
A = np.array([[2,1],[1,2]])
e_value, e_vectors = np.linalg.eig(A)

print("eiganvalue:", e_value)
print("eiganvector:", e_vectors)

eiganvalue: [3. 1.]
eiganvector: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [34]:
A = np.array([[4,7],[2,6]])
A_inv = np.linalg.inv(A)
print(A_inv)

identity= np.dot(A, A_inv)
print(identity)


[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
